# permissions for end users to view decisionmakers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lwmecps-operator
    app.kubernetes.io/managed-by: kustomize
  name: decisionmaker-viewer-role
rules:
- apiGroups:
  - mecdms.apps.lwmecps.com
  resources:
  - decisionmakers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mecdms.apps.lwmecps.com
  resources:
  - decisionmakers/status
  verbs:
  - get
