# permissions for end users to edit decisionmakers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-operator-for-lwmecps
    app.kubernetes.io/managed-by: kustomize
  name: decisionmaker-editor-role
rules:
- apiGroups:
  - mecdms.apps.lwmecps.com
  resources:
  - decisionmakers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mecdms.apps.lwmecps.com
  resources:
  - decisionmakers/status
  verbs:
  - get
